# Generated by Django 2.2.6 on 2019-11-22 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='master',
            name='master_service',
            field=models.ManyToManyField(to='main_app.Service'),
        ),
    ]
