# Generated by Django 2.2.6 on 2019-11-23 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20191123_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='free_time',
            field=models.ManyToManyField(null=True, to='main_app.FreeTime'),
        ),
    ]
