# Generated by Django 2.2.6 on 2019-11-23 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20191123_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='free_time',
            field=models.ManyToManyField(to='main_app.FreeTime'),
        ),
    ]
