# Generated by Django 2.2.6 on 2019-11-24 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20191123_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='free_time',
            field=models.ManyToManyField(to='main_app.FreeTime'),
        ),
    ]
