# Generated by Django 2.2.6 on 2019-11-25 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_remove_service_free_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Records',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('user_name', models.CharField(max_length=20)),
                ('visit_time', models.DateTimeField()),
            ],
        ),
    ]
