# Generated by Django 2.2.6 on 2019-11-27 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_records'),
    ]

    operations = [
        migrations.AddField(
            model_name='freetime',
            name='free_or_not',
            field=models.BooleanField(default=True),
        ),
    ]
