# Generated by Django 2.2.6 on 2019-11-27 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_freetime_free_or_not'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('user_name', models.CharField(max_length=20)),
                ('visit_time', models.DateTimeField()),
                ('master_name', models.CharField(default='Ann', max_length=20)),
            ],
            options={
                'verbose_name': 'Запись',
                'verbose_name_plural': 'Записи',
            },
        ),
        migrations.DeleteModel(
            name='Records',
        ),
    ]
