# Generated by Django 2.2.6 on 2019-11-27 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_auto_20191127_1300'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Record',
        ),
    ]
